before_script:
  - dotnet restore

stages:
  - build

build:
  stage: build
  script:
    - set
    - dotnet build --configuration Release
    - dotnet pack --configuration Release -p:PackageVersion=5.4.%CI_PIPELINE_IID% --include-symbols --include-source --output nupkgs
    - nuget.exe push Rebus.AwsSnsAndSqs.5.4.%CI_PIPELINE_IID%.nupkg "$K8S_SECRET_NUGET_API_KEY"