version: "3.2"
services:
  sqs-mock:
    image: roribio16/alpine-sqs:latest
    container_name: sqs-mock
    ports:
      - "9324:9324"
      - "9325:9325"
    networks:
      - default
  sns-mock:
    image: s12v/sns
    container_name: sns-mock
    ports:
      - "9911:9911"
    networks:
      - default
    volumes:
      - ./config/db.json:/etc/sns/db.json
    depends_on:
      - sqs-mock
      
networks:
  default:
    name: SnsAndSqs