name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
    - uses: actions/checkout@v2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build the stack
      run: docker-compose up -d
    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
