name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
      env:
        CI_COMMIT_BRANCH: ${{ github.head_ref }}
        CI_COMMIT_REF_PROTECTED: ${{ github.ref_protected }}
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        CI_PIPELINE_IID: ${{ github.run_number }}
